### ISSUE TITLE
JsonSchema4.FromTypeAsync<T>().Result just goes into lockdown

### ISSUE THREAD

**Issue by zinvob** [RSuter/NJsonSchema#333]
After upgrading to the new NJsonSchema and using this instead of FromType<T>, it just locks up and never returns. Seems like when you get an error when it's processing it never returns properly or gives an exception. The same code did not give any exceptions before and returned a normal Schema (v5.7.6142.39228).

T is Someclass.InProperties
public Someclass
  {
  public class InProperties : SqlExecutor.ConnectionProperties
        {
            [DefaultValue(30)]
            public int? SecondsRepeat { get; set; } = 30;
            [DefaultValue(10)]
            public int? SecondsChangeIdle { get; set; } = 10;
        }
  }

so there is inheritance, maybe that's a problem in the new version?

Here's the rest:
public class SqlExecutor : ISqlExecutor
    {
        public class ConnectionProperties : JsonClass
        {
            [DefaultValue(DatabaseType.SqlServer)]
            public DatabaseType DatabaseType { get; set; } = DatabaseType.SqlServer;
            public string Server { get; set; }
            public string Database { get; set; }
            public bool IntegratedSecurity { get; set; }
            public string Username { get; set; }
            public string Password { get; set; }
        }
  }

public enum DatabaseType
    {
        SqlServer = 1,
        [Obsolete("Støtte for Oracle DBMS er foreløpig ikke implementert")]
        Oracle = 2
    }

**Comment by rsuter** [comment]
Try `var schema = Task.Run(() => JsonSchema4.FromTypeAsync()).GetAwaiter().GetResult()`

**Comment by zinvob** [comment]
This won't do in the long run. There must be a way to run FromType without using async.. I don't want to make a task (thread) every time this executes..

**Comment by zinvob** [comment]
This is the schema data that I get from this code:

{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "title": "InProperties",
  "additionalProperties": false,
  "properties": {
    "SecondsRepeat": {
      "type": [
        "integer",
        "null"
      ],
      "format": "int32",
      "default": 30
    },
    "SecondsChangeIdle": {
      "type": [
        "integer",
        "null"
      ],
      "format": "int32",
      "default": 10
    }
  },
  "definitions": {
    "ConnectionProperties": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "DatabaseType": {
          "oneOf": [
            {
              "$ref": "#/definitions/DatabaseType"
            }
          ],
          "default": 1
        },
        "Server": {
          "type": [
            "null",
            "string"
          ]
        },
        "Database": {
          "type": [
            "null",
            "string"
          ]
        },
        "IntegratedSecurity": {
          "type": "boolean"
        },
        "Username": {
          "type": [
            "null",
            "string"
          ]
        },
        "Password": {
          "type": [
            "null",
            "string"
          ]
        }
      },
      "allOf": [
        {
          "$ref": "#/definitions/JsonClass"
        }
      ]
    },
    "DatabaseType": {
      "type": "integer",
      "x-enumNames": [
        "SqlServer",
        "Oracle"
      ],
      "enum": [
        1,
        2
      ],
      "description": ""
    },
    "JsonClass": {
      "type": "object",
      "additionalProperties": false
    }
  },
  "allOf": [
    {
      "$ref": "#/definitions/ConnectionProperties"
    }
  ]
}

Why is not DatabaseType, Server, Database, IntegratedSecurity, Username and Password also part of schema.properties. You only find it under definitions now. Any json parser, like json.net will parse all this as one and include all properties, and then you get validation problems.

**Comment by moh-hassan** [comment]
The valid approach to use the new Asynchronous of NJS library (which is better than Synchronous programing in v5) is using the TPL async/await. 
 
As you said: "I don't want to make a task (thread) every time this executes.."
Really, Asynchronous programming in (JsonSchema4.FromTypeAsync) don't cause additional threads to be created.

Have a look to MSDN article: [MSDN: Asynchronous Programming with async and await](https://msdn.microsoft.com/en-us/library/mt674882.aspx#Anchor_4)
excerpt from MSDN:

`The async and await keywords don't cause additional threads to be created. Async methods don't require multithreading because an async method doesn't run on its own thread. The method runs on the current synchronization context and uses time on the thread only when the method is active.
`
await  JsonSchema4.FromTypeAsync<T>()   don't mean that it will create another thread.

**As a fact, Task<T>.Result would block until the task had been  completed**.

you can use FromTypeAsync<T> as in the following example:

          async Task MyTask()
          {
              //await  don't mean that it will create another thread.
             var schema = await JsonSchema4.FromTypeAsync<T>().ConfigureAwait(false);
             var json = schem.ToJson();
              ....

          return;
         }

If the RunTime is seeing that the  method which is called with await in your async method is delayed, it is exiting from that method and waits after awaited methods finish and then continue that method with another thread

await task; will "yield" the current thread,              but  task.Result will block the current thread. 
await   will not block, it's an asynchronous wait;    Result is a blocking wait.
