### ISSUE TITLE
Question: is it possible to validate json schema syntax itself?

### ISSUE THREAD

**Issue by sberserker** [RSuter/NJsonSchema#386]
Say i have json schema provided. Is it possible to detect invalid elements in it like type1, sting1 using the library?
```
{
    "title": "Person",
    "type": "object",
    "properties": {
        "firstName": {
            "type1": "string1"
        },
        "lastName": {
            "type": "string"
        }
    },
    "required": ["firstName", "lastName"]
}
```

**Comment by RSuter** [comment]
Additional properties are serialized to the ExtensionData property (no error). If a schema property is incorrectly used (i.e. type is an object instead of a string) you'll get an exception... So the answer is mostly "no". 

But you should try to load the json meta-schema (the schema to validate schemas) and validate your schema...

**Comment by sberserker** [comment]
Using meta-schema should work.
I'll try this one. It's v0.6 but good place to start with.
https://github.com/json-schema-org/json-schema-spec/blob/master/schema.json

Thanks!
