### ISSUE TITLE
type: date format is not formatted correctly in c#

### ISSUE THREAD

**Issue by danzel** [RSuter/NJsonSchema#491]
When a `"type": "date"` property is present in a schema we can generate a DateTime or DateTimeOffset field.
However, when when serializing this field it is not turned in to a date, it is turned in to a dateTime.

ref: https://swagger.io/specification/#document-structure-12
date should be a full-date, which is `yyyy-MM-dd` in c#.

To fix this, you can add `[Newtonsoft.Json.JsonConverter(typeof(DateFormatConverter))]` to the Property and define that converter as:
```
	public class DateFormatConverter : Newtonsoft.Json.Converters.IsoDateTimeConverter
	{
		public DateFormatConverter()
		{
			DateTimeFormat = "yyyy-MM-dd";
		}
	}
```

Trying to figure out how to fix this myself, but... there is a lot of code in here :)

**Comment by danzel** [comment]
Figured out the typescript version, but I'm not sure how to best implement it for c#, some help or advice here would be greatly appreciated. Thanks!

**Comment by RSuter** [comment]
I dont like to add more helper classes to the output (i.e. DateFormatConverter) but it seems that this is the only solution. The question is whether we generate this as a global type (potential name collisions) or as inline time in each class (more code, repetitions).

**Comment by danzel** [comment]
We may need to do it in each class, otherwise if they generate multiple
clients in the same project we’ll cause a collision :(

**Comment by RSuter** [comment]
Yes, this is exactly the problem (I think its a rare case, because it only happens when generating multiple clients from **multiple swagger specs**). I still prefer the "single utility class" option because we already have this problem with the JsonInheritanceConverter. However we should add the option GenerateDateFormatConverter (default: true) so that you can disable the generation for all but one generation (we also have GenerateJsonInheritanceConverter)

**Comment by danzel** [comment]
Ah yeah, that seems like a good way to do it.
I'll try take a look at this one tomorrow.

(Reminder to self: `NJsonSchema.CodeGeneration.CSharp/Templates/ClassTemplate.tt`)

**Comment by RSuter** [comment]
The actual class is rendered in FileTemplate.tt
