### ISSUE TITLE
How to set jsonserializer setting in generator code

### ISSUE THREAD

**Issue by lisemon** [RSuter/NJsonSchema#495]
Hi,
I am generating C# code based on json schemas, and for date-time I am using DateTimeOffset.

So, `csharpGenerator.Settings.DateTimeType = "System.DateTimeOffset"` works fantastic.

Is there anyway that I can set the the default `Newtonsoft.Json.JsonSerializerSetting.DateParseHandling` to `DateTimeOffset` in the generator code? Currently when reading dates from json they are converted to local time, instead of keeping the original timezone.

If this cannot be done, do you suggest writing a specific converter for DateTimeOffset?

Thanks.

**Comment by RSuter** [comment]
I dont think you can add a custom converter because ToJson uses JsonConverter without settings (or they are not customizable).

 Is this something we should hardcode for DateTimeOffset (ie it is wrong for everyone) or should we try to find a solution to customize the serializer settings? 

In the future im planning to provide a flexible templating engine so that you could replace only the template for the ToJson() method, but there is still a lot of work until this is finished.

**Comment by lisemon** [comment]
Currently I have played around with forking your repo, and hardcoded it to `DateTimeOffset` in `CSharpJsonSerializerGenerator` and `JsonInheritanceConverterTemplate.cs`. And that works.

I think it would be sweet to be able to pass settings for to the JsonSerializerSetting.
https://www.newtonsoft.com/json/help/html/T_Newtonsoft_Json_JsonSerializerSettings.htm

I am using DateTimeOffset to preserve the timezone that is passed in my iso string. With it being parsed as DateTime this date is converted to local time (!?). And as long as the `JsonSerializer` setting is using DateParseHandling.DateTime, it does not provide much value to generate classes that uses DateTimeOffset, at least for me. 😄
