### ISSUE TITLE
Add support to Localized DisplayAttribute

### ISSUE THREAD

**Issue by alb3ric** [RSuter/NJsonSchema#512]
Hello,

It would be great if JsonSchemaGenerator was handling the ResoureType property of the DisplayAttribute. We could then generate localized schema.

Ex : 
[Display(ResourceType = typeof(MyResources), Name = "MyString")]

Regards,

**Comment by RSuter** [comment]
The project supports

    <TargetFrameworks>netstandard1.0;net40;net45</TargetFrameworks>

and I'm pretty sure that ResourceManager is not available in netstandard1.0.

The simplest solution would be to make ApplyDataAnnotations virtual so that you can implement your own generator extending this method. Otherwise we need to implement the ResourceManager code with reflection or `#if` only for the supported FWs.

**Comment by alb3ric** [comment]
Ok, I had a doubt about resourcemanager :)

Yoy are right, paking the applydataannotations virtual seems a good solution.
